### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by swushi** [swushi/react-native-input-outline#12]

**Comment by swushi** [comment]
This was already working as expected. Opened by mistake. Simply provide the `multiline` prop to the component.

**Comment by ftzi** [comment]
![image](https://user-images.githubusercontent.com/28177550/136644497-439b4bd6-5720-40f1-87f8-4244bce70354.png)


I think there should be a inputStyle property, so we can interact with it directly.

I added a `textAlignVertical: 'top'` to the code input style and the input is correctly aligned.

Edit: Beware that this align will move singleline text above by a little. Maybe the default could be this align top, and you could then set the default y to a little lower to compensate it
