### ISSUE TITLE
Size of placeholder text and assistive text should be configurable

### ISSUE THREAD

**Issue by braincore** [swushi/react-native-input-outline#2]
The default sizes appear too small to me which is why it's an immediate issue, but regardless, the sizes should be configurable for interfaces that offer adjustable text sizes.

**Comment by swushi** [comment]
fixed with #4

**Comment by braincore** [comment]
Thanks for the changes! How about making the label's size (placeholder when in top-left corner) also configurable?

On a design note, I have a suggestion (don't feel any pressure to incorporate it). You now have identical configurability for `font`, `error`, `assistive`, `characterCount`, and maybe `label`. But in all likelihood, `error`, `assistive`, `characterCount`, and `label` will have matching font size and family. Perhaps having only two categories (placeholder vs. everything else) of font configuration would be simpler.
