### ISSUE TITLE
Text is jumping a little during input 

### ISSUE THREAD

**Issue by KestasVenslauskas** [swushi/react-native-input-outline#6]
As title says text is jumping horizontally a little while writing something.
This is fixed by adding {flex:1} to TextInput itself on the style.

**Comment by swushi** [comment]
If you're up for it, feel free to submit a PR.. won't be available for a little while to fix. See CONTRIBUTING.md

**Comment by swushi** [comment]
fixed with eb0622c707aa95e5effd963ed138ee42260357f7

Although I was not able to reproduce your issue, adding `flex: 1` to the `TextInput` did not affect anything as far as I could tell. Please report back if this fixed your issue. Closing for now, feel free to reopen if the issue persists.
