### ISSUE TITLE
ReferenceError: Cant't find variable _globalSetter after running yarn add command from the Repo intro

### ISSUE THREAD

**Issue by me1k** [swushi/react-native-input-outline#9]
This is the Error i get directly after pod-install and rebuild the RN App.

My App runs without issues before:

`ReferenceError: Can't find variable: _globalSetter
[Wed Mar 24 2021 13:31:11.965]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Wed Mar 24 2021 13:31:13.700]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

**Comment by swushi** [comment]
This is a known issue with Reanimated v2 installation. Most commonly, forgetting the Babel plugin. Please verify you have installed reanimated v2 correctly. I will also update the docs to clearly point out this is necessary.

**Comment by me1k** [comment]
Hmm .. on the Documentation is stated, that on iOS everything works automatically, after you added the babel plugin.
I cleared cache, removed node_modules ran pod-install but still the same issue

EDIT:
yarn add core-js@^3 did it for me
